### ISSUE TITLE
packagist.org: The netresearch/contexts_geolocation package of which you are a maintainer has failed to update due to invalid data contained in your composer.json.

### ISSUE THREAD

**Issue by CybotTM** [netresearch/t3x-contexts_geolocation#4]
The netresearch/contexts_geolocation package of which you are a maintainer has failed to update due to invalid data contained in your composer.json.
Please address this as soon as possible since the package stopped updating.

It is recommended that you use `composer validate` to check for errors when you
change your composer.json.

Below is the full update log which should highlight errors as
"Skipped branch ...":

[Composer\Repository\InvalidRepositoryException]: Some branches contained invalid data and were discarded, it is advised to review the log and fix any issues present in branches

Reading composer.json of netresearch/contexts_geolocation (v1.0.0)
Found cached composer.json of netresearch/contexts_geolocation (v1.0.0)
Reading composer.json of netresearch/contexts_geolocation (v0.4.1)
Skipped v0.4.1, no composer file (cached from ref 8aafc4501f8d4c3cefaf3c9f4a931c685a8d32ee)
Reading composer.json of netresearch/contexts_geolocation (v0.4.0)
Skipped v0.4.0, no composer file (cached from ref 8e14840e4b50a8ed99b9dbc2df81451f9ce78021)
Reading composer.json of netresearch/contexts_geolocation (v0.3.1)
Skipped v0.3.1, no composer file (cached from ref 244c144b136bafbdf898cf64a58f550da088f8fe)
Reading composer.json of netresearch/contexts_geolocation (v0.3.0)
Skipped v0.3.0, no composer file (cached from ref 76537c1e02e7e86b8bee5fdd7a09220686920342)
Reading composer.json of netresearch/contexts_geolocation (v0.2.2)
Skipped v0.2.2, no composer file (cached from ref 0ba3ea6d8004eaa85395ef09f7fc52bae745d695)
Reading composer.json of netresearch/contexts_geolocation (v0.2.1)
Skipped v0.2.1, no composer file (cached from ref 7e87a4843a32b4c90c90d1c41f4490bb5b1fbeb1)
Reading composer.json of netresearch/contexts_geolocation (v0.2.0)
Skipped v0.2.0, no composer file (cached from ref c8e0182597f5c9d91b545f1f7a07b0b3194ea001)
Reading composer.json of netresearch/contexts_geolocation (master)
Importing branch master (dev-master)
Skipped branch master, Invalid package information:
Deprecation warning: replace.contexts_geolocation is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$". Make sure you fix this as Composer 2.0 will error.
Deprecation warning: require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead. Make sure you fix this as Composer 2.0 will error.

Reading composer.json of netresearch/contexts_geolocation (0.4.x)
Skipped 0.4.x-dev, no composer file (cached from ref 4a7eca8c9cdc1666320fbaa2783b4415a2b809b6)

**Comment by Gitsko** [comment]
Hi @CybotTM ,

i don't see any problem on packagist.org at the moment, i think the problem is fixed by now with the latest composer.json file or ?

**Comment by CybotTM** [comment]
Hi @Gitsko,

the problem persists, the relevant part is now:

> Skipped branch master, Invalid package information:
> replace.netresearch/contexts_geolocation : a package cannot set a replace on itself

But looking at packagist clearly states the error(s):

https://packagist.org/packages/netresearch/contexts_geolocation

![image](https://github.com/netresearch/t3x-contexts_geolocation/assets/326348/f3990417-e16c-4b72-9443-0c5357841faf)

(You need to be logged in as maintainer)

**Comment by Gitsko** [comment]
Hi @CybotTM ,

thank you for the explanation, i fix the composer json file, set a new Tag and Release.

Composer validate shows `./composer.json is valid`.

Packagiist update now the package.

I think we can close this issue.
